server:
  port: 8888
  servlet:
    context-path: /incomeExpense

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mzl.incomeexpensemanagesystem.entity
  type-enums-package: com.mzl.incomeexpensemanagesystem.enums
  # MyBatis 原生支持的配置
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    # 在控制台打印SQL命令并打印执行结果
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 在控制台打印SQL命令不打印结果
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 全局策略配置
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      #查询时不用判空
      select-strategy: not_empty

#spring相关配置
spring:
  # 激活环境
  profiles:
    active: dev
#    active: pro
  servlet:
    multipart:
      #单个文件上传大小
      max-file-size: 10MB
      #总数据上传大小
      max-request-size: 100MB

  #thymeleaaf
  thymeleaf:
    mode: html
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  #开启热部署
  devtools:
    restart:
      enabled: true

  # 允许循环依赖
  main:
    allow-circular-references: true


